-- Ran on completely connected 3 node graph
-- Should return 24
-- three start nodes
-- Each start node has two possible final nodes for their traversal
-- two ways to get to intermediate node 
-- two ways to get from intermediate node to final node
-- 3*2*2*2 = 24

FROM c3 
MATCH ACYCLIC (a) -[]- (b) -[]- (c)
RETURN COUNT(*)
