-- +----------------------+----+---------------------------------------------+----------------+
-- | Operator             | Id | Details                                     | Estimated Rows |
-- +----------------------+----+---------------------------------------------+----------------+
-- | +ProduceResults      |  0 | count                                       |              1 |
-- | |                    +----+---------------------------------------------+----------------+
-- | +EagerAggregation    |  1 | count(*) AS count                           |              1 |
-- | |                    +----+---------------------------------------------+----------------+
-- | +Filter              |  2 | NOT anon_8 = anon_7 AND NOT anon_7 = anon_6 |              1 |
-- | |                    +----+---------------------------------------------+----------------+
-- | +Expand(Into)        |  3 | (person2)-[anon_7:KNOWS]-(person3)          |              1 |
-- | |                    +----+---------------------------------------------+----------------+
-- | +NodeHashJoin        |  4 | person2, country                            |             62 |
-- | |\                   +----+---------------------------------------------+----------------+
-- | | +Filter            |  5 | NOT anon_8 = anon_6 AND person2:Person      |           6971 |
-- | | |                  +----+---------------------------------------------+----------------+
-- | | +Expand(All)       |  6 | (person1)-[anon_6:KNOWS]-(person2)          |           6971 |
-- | | |                  +----+---------------------------------------------+----------------+
-- | | +Expand(Into)      |  7 | (person3)-[anon_8:KNOWS]-(person1)          |            327 |
-- | | |                  +----+---------------------------------------------+----------------+
-- | | +NodeHashJoin      |  8 | country                                     |          26036 |
-- | | |\                 +----+---------------------------------------------+----------------+
-- | | | +Expand(All)     |  9 | (city3)-[anon_5:IS_PART_OF]->(country)      |           1700 |
-- | | | |                +----+---------------------------------------------+----------------+
-- | | | +Filter          | 10 | city3:City                                  |           1700 |
-- | | | |                +----+---------------------------------------------+----------------+
-- | | | +Expand(All)     | 11 | (person3)-[anon_4:IS_LOCATED_IN]->(city3)   |           1700 |
-- | | | |                +----+---------------------------------------------+----------------+
-- | | | +NodeByLabelScan | 12 | person3:Person                              |           1700 |
-- | | |                  +----+---------------------------------------------+----------------+
-- | | +Filter            | 13 | country:Country                             |           1700 |
-- | | |                  +----+---------------------------------------------+----------------+
-- | | +Expand(All)       | 14 | (city1)-[anon_1:IS_PART_OF]->(country)      |           1700 |
-- | | |                  +----+---------------------------------------------+----------------+
-- | | +Filter            | 15 | city1:City                                  |           1700 |
-- | | |                  +----+---------------------------------------------+----------------+
-- | | +Expand(All)       | 16 | (person1)-[anon_0:IS_LOCATED_IN]->(city1)   |           1700 |
-- | | |                  +----+---------------------------------------------+----------------+
-- | | +NodeByLabelScan   | 17 | person1:Person                              |           1700 |
-- | |                    +----+---------------------------------------------+----------------+
-- | +Filter              | 18 | country:Country                             |           1700 |
-- | |                    +----+---------------------------------------------+----------------+
-- | +Expand(All)         | 19 | (city2)-[anon_3:IS_PART_OF]->(country)      |           1700 |
-- | |                    +----+---------------------------------------------+----------------+
-- | +Filter              | 20 | city2:City                                  |           1700 |
-- | |                    +----+---------------------------------------------+----------------+
-- | +Expand(All)         | 21 | (person2)-[anon_2:IS_LOCATED_IN]->(city2)   |           1700 |
-- | |                    +----+---------------------------------------------+----------------+
-- | +NodeByLabelScan     | 22 | person2:Person                              |           1700 |
-- +----------------------+----+---------------------------------------------+----------------+


-- Huh???

FROM lsqb01
MATCH 
    (person2:Person)-[:isLocatedIn]->(city2:City)-[:isPartOf]->(country),
    (person1:Person)-[:isLocatedIn]->(city1:City)-[:isPartOf]->(country),
    (person3:Person)-[:isLocatedIn]->(city3:City)-[:isPartOf]->(country),

    -- (person1:Person)-[:isLocatedIn]->(city1:City)-[:isPartOf]->(country),
    -- (person3)-[:knows]-(person1),
    -- (person1)-[:knows]-(person2:Person),
    -- (person2:Person)-[:isLocatedIn]->(city2:City)-[:isPartOf]->(country),
    -- (person2:Person)-[:isLocatedIn]->(city2:City)-[:isPartOf]->(country),
    -- (person2)-[:knows]-(person3)
RETURN COUNT(*)