-- using message doesn't work because there is no message table 
-- MESSAGE = COMMENT UNION POST

-- +-------------------+----+------------------------------------------------------+----------------+
-- | Operator          | Id | Details                                              | Estimated Rows |
-- +-------------------+----+------------------------------------------------------+----------------+
-- | +ProduceResults   |  0 | count                                                |              1 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +EagerAggregation |  1 | count(*) AS count                                    |              1 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Filter           |  2 | NOT tag1 = tag2 AND NOT anon_2 = anon_0 AND tag2:Tag |         185415 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Expand(All)      |  3 | (comment)-[anon_2:HAS_TAG]->(tag2)                   |         208098 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Filter           |  4 | comment:Comment                                      |         177327 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Expand(All)      |  5 | (message)<-[anon_1:REPLY_OF]-(comment)               |         177327 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Filter           |  6 | message:Message                                      |         319227 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Expand(All)      |  7 | (tag1)<-[anon_0:HAS_TAG]-(message)                   |         373740 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +NodeByLabelScan  |  8 | tag1:Tag                                             |          16080 |
-- +-------------------+----+------------------------------------------------------+----------------+

MATCH (tag1:Tag)<-[:hasTag]-(message:Comment | Post)<-[:replyOf]-(comment:Comment)-[:hasTag]->(tag2:Tag)
WHERE tag1 <> tag2
RETURN COUNT(*)