-- +----------------------+----+--------------------------------------------------------------+----------------+
-- | Operator             | Id | Details                                                      | Estimated Rows |
-- +----------------------+----+--------------------------------------------------------------+----------------+
-- | +ProduceResults      |  0 | count                                                        |              1 |
-- | |                    +----+--------------------------------------------------------------+----------------+
-- | +EagerAggregation    |  1 | count(*) AS count                                            |              1 |
-- | |                    +----+--------------------------------------------------------------+----------------+
-- | +OptionalExpand(All) |  2 | (message)<-[anon_3:LIKES]-(liker) WHERE liker:Person         |         319227 |
-- | |                    +----+--------------------------------------------------------------+----------------+
-- | +OptionalExpand(All) |  3 | (message)<-[anon_4:REPLY_OF]-(comment) WHERE comment:Comment |         319227 |
-- | |                    +----+--------------------------------------------------------------+----------------+
-- | +Filter              |  4 | creator:Person                                               |         319227 |
-- | |                    +----+--------------------------------------------------------------+----------------+
-- | +Expand(All)         |  5 | (message)-[anon_2:HAS_CREATOR]->(creator)                    |         319227 |
-- | |                    +----+--------------------------------------------------------------+----------------+
-- | +Filter              |  6 | message:Message                                              |         319227 |
-- | |                    +----+--------------------------------------------------------------+----------------+
-- | +Expand(All)         |  7 | (anon_0)<-[anon_1:HAS_TAG]-(message)                         |         373740 |
-- | |                    +----+--------------------------------------------------------------+----------------+
-- | +NodeByLabelScan     |  8 | anon_0:Tag                                                   |          16080 |
-- +----------------------+----+--------------------------------------------------------------+----------------+


-- MESSAGE = COMMENT UNION POST
-- (:Message) == (:Comment | Post)
MATCH (:Tag)<-[:hasTag]-(message:Comment | Post)-[:hasCreator]->(creator:Person)
OPTIONAL MATCH (message)<-[:replyOf]-(comment:Comment)
OPTIONAL MATCH (message)<-[:likes]-(liker:Person)
RETURN COUNT(*)