-- MESSAGE = COMMENT UNION POST
-- (:Message) -> (:Comment | Post)

-- +-------------------+----+------------------------------------------------------+----------------+
-- | Operator          | Id | Details                                              | Estimated Rows |
-- +-------------------+----+------------------------------------------------------+----------------+
-- | +ProduceResults   |  0 | count                                                |              1 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +EagerAggregation |  1 | count(*) AS count                                    |              1 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Filter           |  2 | NOT tag1 = tag2 AND NOT anon_2 = anon_0 AND tag2:Tag |         185415 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Expand(All)      |  3 | (comment)-[anon_2:HAS_TAG]->(tag2)                   |         208097 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Filter           |  4 | comment:Comment                                      |         177326 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +AntiSemiApply    |  5 |                                                      |         177326 |
-- | |\                +----+------------------------------------------------------+----------------+
-- | | +Expand(Into)   |  6 | (comment)-[anon_3:HAS_TAG]->(tag1)                   |             10 |
-- | | |               +----+------------------------------------------------------+----------------+
-- | | +Argument       |  7 | tag1, comment                                        |         177327 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Expand(All)      |  8 | (message)<-[anon_1:REPLY_OF]-(comment)               |         177327 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Filter           |  9 | message:Message                                      |         319227 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +Expand(All)      | 10 | (tag1)<-[anon_0:HAS_TAG]-(message)                   |         373740 |
-- | |                 +----+------------------------------------------------------+----------------+
-- | +NodeByLabelScan  | 11 | tag1:Tag                                             |          16080 |
-- +-------------------+----+------------------------------------------------------+----------------+


MATCH (tag1:Tag)<-[:hasTag]-(message: Comment | Post)<-[:replyOf]-(comment:Comment)
    WHERE NOT EXISTS (comment)-[:hasTag]->(tag1)
MATCH (comment:Comment)-[:hasTag]->(tag2:Tag)
    -- WHERE tag1 <> tag2 -- this is redundant and hence removed
RETURN COUNT(*)