-- +---------------------+----+-----------------------------------------------+----------------+
-- | Operator            | Id | Details                                       | Estimated Rows |
-- +---------------------+----+-----------------------------------------------+----------------+
-- | +ProduceResults     |  0 | count                                         |              1 |
-- | |                   +----+-----------------------------------------------+----------------+
-- | +EagerAggregation   |  1 | count(*) AS count                             |              1 |
-- | |                   +----+-----------------------------------------------+----------------+
-- | +NodeHashJoin       |  2 | person3                                       |       15659366 |
-- | |\                  +----+-----------------------------------------------+----------------+
-- | | +Filter           |  3 | NOT person1 = person3 AND NOT anon_1 = anon_0 |         773831 |
-- | | |                 +----+-----------------------------------------------+----------------+
-- | | +TriadicSelection |  4 | WHERE NOT (person1)--(person3)                |         773831 |
-- | | |\                +----+-----------------------------------------------+----------------+
-- | | | +Expand(All)    |  5 | (person2)-[anon_1:KNOWS]-(person3)            |           3044 |
-- | | | |               +----+-----------------------------------------------+----------------+
-- | | | +Argument       |  6 | person2, anon_0                               |          36270 |
-- | | |                 +----+-----------------------------------------------+----------------+
-- | | +Filter           |  7 | person2:Person                                |          36270 |
-- | | |                 +----+-----------------------------------------------+----------------+
-- | | +Expand(All)      |  8 | (person1)-[anon_0:KNOWS]-(person2)            |          36270 |
-- | | |                 +----+-----------------------------------------------+----------------+
-- | | +NodeByLabelScan  |  9 | person1:Person                                |           1700 |
-- | |                   +----+-----------------------------------------------+----------------+
-- | +Filter             | 10 | tag:Tag                                       |          39170 |
-- | |                   +----+-----------------------------------------------+----------------+
-- | +Expand(All)        | 11 | (person3)-[anon_2:HAS_INTEREST]->(tag)        |          39170 |
-- | |                   +----+-----------------------------------------------+----------------+
-- | +NodeByLabelScan    | 12 | person3:Person                                |           1700 |
-- +---------------------+----+-----------------------------------------------+----------------+

-- MATCH (person1:Person)-[:knows]-(person2:Person)-[:knows]-(person3:Person)-[:hasInterest]->(tag:Tag)
-- WHERE NOT EXISTS (person1)-[:knows]-(person3)
-- AND person1 <> person3
-- RETURN COUNT(*)

MATCH (person3: Person)-[:hasInterest]->(tag:Tag),
      (person1:Person)-[:knows]-(person2:Person),
      (person2)-[:knows]-(person3)
WHERE NOT EXISTS (person1)-[:knows]-(person3)
    AND person1 <> person3
RETURN COUNT(*)