-- using message doesn't work because there is no message table 
-- MESSAGE = COMMENT UNION POST

MATCH (:Tag)<-[:hasTag]-(message:Comment|Post)-[:hasCreator]->(creator:Person),
    (message)<-[:likes]-(liker:Person),
    (message)<-[:replyOf]-(comment:Comment)
RETURN COUNT(*)