MATCH (:TagCla)<-[:hasType]- -- 16080
      (:Tag)<-[:hasTag]- -- 252881
      (:Comment)-[:replyOf]-> -- 107461
      (:Post)<-[:containerOf]- -- 172438
      (:Forum)-[:hasMember]-> -- 273866
      (:Person)-[:isLocatedIn]-> -- 1700
      (:City) -[:isPartOf]-> (:Country) -- 1343
RETURN COUNT(*)
