MATCH
    (person1:Person)<-[:hasCreator]-(comment:Comment) -- 215488
    -[:replyOf]->(post:Post) -- 107461
    -[:hasCreator]->(person2:Person), -- 172438
    (person1)-[:knows]-(person2) -- 18135
RETURN COUNT(*)