MATCH (:Country)<-[:isPartOf]-(:City)
      <-[:isLocatedIn]-(:Person)<-[:hasMember]-(:Forum)
      -[:containerOf]->(:Post)<-[:replyOf]-(:Comment)
      -[:hasTag]->(:Tag)-[:hasType]->(:TagCla)
RETURN COUNT(*)