-- using message doesn't work because there is no message table 
-- MESSAGE = COMMENT UNION POST

MATCH 
(message:Comment|Post)-[:hasTag]->(:Tag),
(message)-[:hasCreator]->(:Person), -- creator
(message)<-[:likes]-(:Person), -- liker
(message)<-[:replyOf]-(:Comment)
RETURN COUNT(*)