-- using message doesn't work because there is no message table 
-- MESSAGE = COMMENT UNION POST

MATCH 
(message_comment:Comment)<-[:hasTag]-(:Tag),
(message_comment)-[:hasCreator]-(:Person), -- creator
(message_comment)<-[:likes]-(:Person), -- liker
(message_comment)<-[:replyOf]-(:Comment),

(message_post:Post)<-[:hasTag]-(:Tag),
(message_post)-[:hasCreator]-(:Person), -- creator
(message_post)<-[:likes]-(:Person), -- liker
(message_post)<-[:replyOf]-(:Comment)

-- won't work
-- will just output cardinality of Post 
-- need to union the results (or just sum counts), or make a union table

RETURN COUNT(*)