-- using message doesn't work because there is no message table 
-- MESSAGE = COMMENT UNION POST

MATCH 
(message:Comment|Post)<-[:hasTag]-(:Tag),
(message)-[:hasCreator]-(:Person), -- creator
(message)<-[:likes]-(:Person), -- liker
(message)<-[:replyOf]-(:Comment),

-- won't work right now
-- need to add support for boolean label expressions

RETURN COUNT(*)