-- using message doesn't work because there is no message table 
-- MESSAGE = COMMENT UNION POST

MATCH 
(message_comment:Comment)-[:hasTag]->(:Tag),
(message_comment)-[:hasCreator]-(:Person), -- creator
(message_comment)<-[:likes]-(:Person), -- liker
(message_comment)<-[:replyOf]-(:Comment),

(message_post:Post)-[:hasTag]->(:Tag),
(message_post)-[:hasCreator]-(:Person), -- creator
(message_post)<-[:likes]-(:Person), -- liker
(message_post)<-[:replyOf]-(:Comment)

-- won't work
-- sum not supported
-- probably breaks key assumptions to have the two aggregates
	-- ought to cartesian product each line, creating a blow out of matched posts
-- simply not correct

RETURN COUNT(message_comment) + COUNT(message_post)
