-- +--------------------+----+-------------------------------------------+----------------+
-- | Operator           | Id | Details                                   | Estimated Rows |
-- +--------------------+----+-------------------------------------------+----------------+
-- | +ProduceResults    |  0 | count                                     |              1 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +EagerAggregation  |  1 | count(*) AS count                         |              1 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +NodeHashJoin      |  2 | anon_6                                    |        2026451 |
-- | |\                 +----+-------------------------------------------+----------------+
-- | | +Expand(All)     |  3 | (anon_4)<-[anon_5:HAS_MEMBER]-(anon_6)    |         273866 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +Filter          |  4 | anon_0:Country                            |           1700 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +Expand(All)     |  5 | (anon_2)-[anon_1:IS_PART_OF]->(anon_0)    |           1700 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +Filter          |  6 | anon_2:City                               |           1700 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +Expand(All)     |  7 | (anon_4)-[anon_3:IS_LOCATED_IN]->(anon_2) |           1700 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +NodeByLabelScan |  8 | anon_4:Person                             |           1700 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +Filter            |  9 | anon_14:TagClass                          |         126108 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +Expand(All)       | 10 | (anon_12)-[anon_13:HAS_TYPE]->(anon_14)   |         126108 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +Filter            | 11 | anon_12:Tag                               |         126108 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +Expand(All)       | 12 | (anon_10)-[anon_11:HAS_TAG]->(anon_12)    |         126108 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +Filter            | 13 | anon_10:Comment                           |         107461 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +Expand(All)       | 14 | (anon_8)<-[anon_9:REPLY_OF]-(anon_10)     |         107461 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +Filter            | 15 | anon_8:Post                               |         172438 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +Expand(All)       | 16 | (anon_6)-[anon_7:CONTAINER_OF]->(anon_8)  |         172438 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +NodeByLabelScan   | 17 | anon_6:Forum                              |          17043 |
-- +--------------------+----+-------------------------------------------+----------------+

MATCH (forum:Forum)-[:containerOf]->(:Post)<-[:replyOf]-(:Comment)-[:hasTag]->(:Tag)-[:hasType]->(:TagCla),
      (person:Person)-[:isLocatedIn]->(:City)-[:isPartOf]->(:Country),
      (forum)-[:hasMember]->(person)
RETURN COUNT(*)