-- +--------------------+----+-------------------------------------------+----------------+
-- | Operator           | Id | Details                                   | Estimated Rows |
-- +--------------------+----+-------------------------------------------+----------------+
-- | +ProduceResults    |  0 | count                                     |              1 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +EagerAggregation  |  1 | count(*) AS count                         |              1 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +NodeHashJoin      |  2 | person2, person1                          |           1335 |
-- | |\                 +----+-------------------------------------------+----------------+
-- | | +Filter          |  3 | NOT anon_3 = anon_1 AND person1:Person    |         107461 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +Expand(All)     |  4 | (comment)-[anon_1:HAS_CREATOR]->(person1) |         107461 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +Filter          |  5 | comment:Comment                           |         107461 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +Expand(All)     |  6 | (post)<-[anon_2:REPLY_OF]-(comment)       |         107461 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +Filter          |  7 | post:Post                                 |         172438 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +Expand(All)     |  8 | (person2)<-[anon_3:HAS_CREATOR]-(post)    |         387926 |
-- | | |                +----+-------------------------------------------+----------------+
-- | | +NodeByLabelScan |  9 | person2:Person                            |           1700 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +Filter            | 10 | person1:Person                            |          36270 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +Expand(All)       | 11 | (person2)-[anon_0:KNOWS]-(person1)        |          36270 |
-- | |                  +----+-------------------------------------------+----------------+
-- | +NodeByLabelScan   | 12 | person2:Person                            |           1700 |
-- +--------------------+----+-------------------------------------------+----------------+

MATCH
    (person2:Person)-[:knows]-(person1:Person),
    (person2)<-[:hasCreator]-(post:Post)<-[:replyOf]-(comment:Comment)-[:hasCreator]->(person1)
RETURN COUNT(*)