-- using message doesn't work because there is no message table 
-- MESSAGE = COMMENT UNION POST

-- +-------------------+----+-------------------------------------------+----------------+
-- | Operator          | Id | Details                                   | Estimated Rows |
-- +-------------------+----+-------------------------------------------+----------------+
-- | +ProduceResults   |  0 | count                                     |              1 |
-- | |                 +----+-------------------------------------------+----------------+
-- | +EagerAggregation |  1 | count(*) AS count                         |              1 |
-- | |                 +----+-------------------------------------------+----------------+
-- | +Filter           |  2 | creator:Person                            |          74236 |
-- | |                 +----+-------------------------------------------+----------------+
-- | +Expand(All)      |  3 | (message)-[anon_2:HAS_CREATOR]->(creator) |          74236 |
-- | |                 +----+-------------------------------------------+----------------+
-- | +Filter           |  4 | anon_0:Tag                                |          74236 |
-- | |                 +----+-------------------------------------------+----------------+
-- | +Expand(All)      |  5 | (message)-[anon_1:HAS_TAG]->(anon_0)      |          74236 |
-- | |                 +----+-------------------------------------------+----------------+
-- | +Filter           |  6 | comment:Comment                           |          90212 |
-- | |                 +----+-------------------------------------------+----------------+
-- | +Expand(All)      |  7 | (message)<-[anon_4:REPLY_OF]-(comment)    |          90212 |
-- | |                 +----+-------------------------------------------+----------------+
-- | +Filter           |  8 | message:Message                           |         162402 |
-- | |                 +----+-------------------------------------------+----------------+
-- | +Expand(All)      |  9 | (liker)-[anon_3:LIKES]->(message)         |         162402 |
-- | |                 +----+-------------------------------------------+----------------+
-- | +NodeByLabelScan  | 10 | liker:Person                              |           1700 |
-- +-------------------+----+-------------------------------------------+----------------+

MATCH
    (liker:Person)-[:likes]->(message:Comment|Post)<-[:replyOf]-(comment:Comment),
    (message)-[:hasTag]->(:Tag),
    (message)-[:hasCreator]->(creator:Person),
RETURN COUNT(*)