-- +----------------------+----+-----------------------------------------------+----------------+
-- | Operator             | Id | Details                                       | Estimated Rows |
-- +----------------------+----+-----------------------------------------------+----------------+
-- | +ProduceResults      |  0 | count                                         |              1 |
-- | |                    +----+-----------------------------------------------+----------------+
-- | +EagerAggregation    |  1 | count(*) AS count                             |              1 |
-- | |                    +----+-----------------------------------------------+----------------+
-- | +NodeHashJoin        |  2 | person3                                       |       15886512 |
-- | |\                   +----+-----------------------------------------------+----------------+
-- | | +Filter            |  3 | NOT person1 = person3 AND NOT anon_1 = anon_0 |         773831 |
-- | | |                  +----+-----------------------------------------------+----------------+
-- | | +NodeHashJoin      |  4 | person2                                       |         773831 |
-- | | |\                 +----+-----------------------------------------------+----------------+
-- | | | +Expand(All)     |  5 | (person3)-[anon_1:KNOWS]-(person2)            |          36270 |
-- | | | |                +----+-----------------------------------------------+----------------+
-- | | | +NodeByLabelScan |  6 | person3:Person                                |           1700 |
-- | | |                  +----+-----------------------------------------------+----------------+
-- | | +Filter            |  7 | person2:Person                                |          36270 |
-- | | |                  +----+-----------------------------------------------+----------------+
-- | | +Expand(All)       |  8 | (person1)-[anon_0:KNOWS]-(person2)            |          36270 |
-- | | |                  +----+-----------------------------------------------+----------------+
-- | | +NodeByLabelScan   |  9 | person1:Person                                |           1700 |
-- | |                    +----+-----------------------------------------------+----------------+
-- | +Filter              | 10 | tag:Tag                                       |          39170 |
-- | |                    +----+-----------------------------------------------+----------------+
-- | +Expand(All)         | 11 | (person3)-[anon_2:HAS_INTEREST]->(tag)        |          39170 |
-- | |                    +----+-----------------------------------------------+----------------+
-- | +NodeByLabelScan     | 12 | person3:Person                                |           1700 |
-- +----------------------+----+-----------------------------------------------+----------------+

MATCH (person3:Person)-[:hasInterest]->(tag:Tag)
MATCH 
    (person3:Person)-[:knows]-(person2:Person),
    (person2)-[:knows]-(person1:Person)
    WHERE person1 <> person3
RETURN COUNT(*)